### ISSUE TITLE
Complete Web Version Prototype of Game

### ISSUE THREAD

**Issue by UniversalTze** [UniversalTze/5-7-Connect-4#1]
# **Description** 
This feature seeks to implement a basic Connect-Four/ Candy Crush game in a HTML format. This HTML version will aim to emulate the behaviour of the arduino so that it will be seamless when we migrate it into a C++ version. 

# **Current Version of Game** 
- Players take turns inserting tokens into respective columns with the aim of creating a line of consecutive tokens.
- These lines can be horizontal, vertical or diagonal. Players earn points for every successful connection, with opportunities for chain reactions and combo scoring.
- At random intervals throughout the game, the board will rotate 90 degrees in a random direction, causing all the tokens to ‘fall’ down, introducing elements of luck and randomness to the gameplay.
- Players are also restricted to a time limit for each of their turns, where if they do not place a token in the allotted time, they will simply miss their turn.

# **Dependencies**
- No dependencies. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Develop structure of game along with functions (Aug. 18)
- [x] Have some version of the game (Aug. 23)
- [x] Complete version of game (Aug. 26)
- [x] Test fully implemented version of game, (Aug. 27)
- [x]  Finish work on additional animations for game (Sep. 14)
