### ISSUE TITLE
C/C++ Version of Connect-4

### ISSUE THREAD

**Issue by UniversalTze** [UniversalTze/5-7-Connect-4#10]
# **Description** 
Now that our HTML version is nearing/basically complete, we need to migrate it into a C/C++ version. 

# **Current Version of Game** 
- Players take turns inserting tokens into respective columns with the aim of creating a line of consecutive tokens.
- These lines can be horizontal, vertical or diagonal. Players earn points for every successful connection, with opportunities for chain reactions and combo scoring.
- At random intervals throughout the game, the board will rotate 90 degrees in a random direction, causing all the tokens to ‘fall’ down, introducing elements of luck and randomness to the gameplay.
- Players are also restricted to a time limit for each of their turns, where if they do not place a token in the allotted time, they will simply miss their turn.
- Animations will appear for token clearing and winning state. 

# **Dependencies**
Web Prototype being close to completed #1 
Hardware prototype to be available to test with arduino. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Migrate working classes into from typescript to C++ (Sep. 21)
- [ ] Test these classes in C++ (Sep. 24)
- [ ]  Migrate additional features if completed in web prototype (Sep. 27)
- [ ]  Run exhaustive tests with physical prototype (Sep 30)

**Comment by UniversalTze** [comment]
The job is done. I can finally rest, as I watch the sun rise on a grateful universe.
