### ISSUE TITLE
Additional Animations for Token Clearing and Win/ Draw Scenarios

### ISSUE THREAD

**Issue by UniversalTze** [UniversalTze/5-7-Connect-4#11]
# **Description**
**Task:** Additional Animations for Token Clearing and Win/ Draw Scenarios
**Feature:** Complete Web Version Prototype of Game (#1)

The team has recognised that certain animations are needed to keep the audience engaged when playing our game. Thus more animations for token clearing and end game scenarios need to be created. 

# **Milestones**
- [x] Develop concepts for different animations (Sep. 9)
- [x] Write code for new concepts (Sep. 9)  
- [x] Integrate with other features of game behaviours. (Sep. 14)
- [x] Test with other features (Sep. 14)  

**Completion Deadline:** Sep.14

# **Members**
- @UniversalTze 
- @haozhi-ryan
