### ISSUE TITLE
Migration of Typescript Files to C/C++

### ISSUE THREAD

**Issue by UniversalTze** [UniversalTze/5-7-Connect-4#12]
# **Description**
**Task:** Migration of Typescript Files to C/C++
**Feature:** Complete Web Version Prototype of Game (#10 )

In order for the hardware to interact with the code we've written, our typescript files need to be converted into C/C++ files. This is so that we can communicate with the arduino to process our game play, linking the hardware board to the software code written. 

# **Milestones**
- [x] Convert Board Class to C/C++ (Sep. 14)
- [x] Convert Board Display Class to C/C++(Sep. 14)  
- [x] Convert Game Class to C/C++ (Sep. 14)
- [x] Convert constant class to C/C++ (Sep. 14)  
- [x] Convert the rest of the classes to C/C++ (Sep. 25)

**Completion Deadline:** Sep.14

# **Members**
- @UniversalTze 
- @pchsa 
- @ThePyromancer1 
- @haozhi-ryan

**Comment by UniversalTze** [comment]
Its done
