### ISSUE TITLE
Game Class/State

### ISSUE THREAD

**Issue by UniversalTze** [UniversalTze/5-7-Connect-4#2]
# **Description**
**Task:** Game Class/State
**Feature:** Complete Web Version Prototype of Game (#1)

The team has recognised that a game state will be needed to manage the flow of gameplay for this project. Features of this include maintaining game score, turn time limit, time until rotation of board, rotation of board and win condition. 

# **Milestones**
- [x] Develop characteristics and game-flow for gameClass (Aug. 18)
- [x] Simple Test Game Class (Aug 24)  
- [x] Integrate with other features of game behaviours. (Aug. 24)
- [x] Test Game Class with other features (Aug 27)  

**Completion Deadline:** Aug. 27

# **Members**
- @UniversalTze
