### ISSUE TITLE
Board Class/State

### ISSUE THREAD

**Issue by UniversalTze** [UniversalTze/5-7-Connect-4#3]
# **Description**
**Task:** Board Class/State (#3).
**Feature:** Complete Web Version Prototype of Game (#1).

The team has recognised that a representation of the board state during the game. Features of this include managing board state, token placement and special behaviours. 

# **Milestones**
- [x] Develop characteristics and game-flow for Board Class (Aug. 18)
- [x] Finish Board Class (Aug. 23)
- [x] Test Board Class (Aug 24)  
- [x] Integrate with other features of game behaviours. (Aug. 27)

**Completion Deadline:** Aug. 27

# **Members**
- @ThePyromancer1
