### ISSUE TITLE
Board Display Class

### ISSUE THREAD

**Issue by UniversalTze** [UniversalTze/5-7-Connect-4#4]
# **Description**
**Task:** Board/Display Class (#4).
**Feature:** Complete Web Version Prototype of Game (#1).

The team has recognised that a board display class will be needed to visualise the state of the game. This task will also to attempt to integrate some animations for when the board rotates or goes through a transition state. 

# **Milestones**
- [x] Develop characteristics and game-flow for Board Display Class (Aug. 18)
- [x] Finish implementing Board Display Class (Aug. 23)
- [x] Test Board Display Class (Aug 24)  
- [x] Integrate with other features of game behaviours. (Aug. 27)

**Completion Deadline:** Aug. 27

# **Members**
- @haozhi-ryan
